# Generated by Django 4.1.4 on 2022-12-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tags_display_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default=''),
        ),
    ]
