# Generated by Django 4.1.4 on 2022-12-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_description_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='male',
        ),
    ]
