# Generated by Django 4.1.4 on 2022-12-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
