# Generated by Django 4.1.4 on 2022-12-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
    ]
