# Generated by Django 4.1.4 on 2022-12-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_roles_remove_project_id_profile_is_verifyied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstoverify',
            name='auth_key',
            field=models.TextField(default='NaN'),
        ),
    ]
