# Generated by Django 4.1.4 on 2022-12-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_profile_role_alter_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='api.roles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='api.tags'),
        ),
    ]
