# Generated by Django 4.1.4 on 2022-12-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profile_roles_alter_profile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('display_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='projectroles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.faculty'),
            preserve_default=False,
        ),
    ]
