# Generated by Django 4.1.4 on 2022-12-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_faculty_alter_projectroles_user_id_project_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='uniq_id',
            field=models.CharField(max_length=50),
        ),
    ]
