# Generated by Django 4.1.4 on 2022-12-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_project_id_alter_project_uniq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterField(
            model_name='project',
            name='uniq_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
