# Generated by Django 4.1.4 on 2022-12-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_project_faculty_remove_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='profiles',
            field=models.ManyToManyField(to='api.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='api.tags'),
        ),
    ]
