# Generated by Django 4.1.4 on 2022-12-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project_faculty_project_profiles_project_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
