# Generated by Django 4.1.4 on 2022-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_project_options_remove_project_id'),
    ]

    operations = [
    ]
